### ISSUE TITLE
Definir dados

### ISSUE THREAD

**Issue by willianjusten** [jugoncalves/cem#1]
Poderia passar aqui quais os dados que temos. Para assim, podermos escolher os melhores.

* Número de links divulgados?
* Número de assinantes?
* Quantidade de envios / mês ou envios/ano?
* Quantidade de cliques?
* Localidades dos assinantes?

**Comment by jugoncalves** [comment]
Acho que não tenho o primeiro e o último. Vou dar olhada melhor nisso. :)

**Comment by BrunoKinoshita** [comment]
Seria bom tem mais informações :cry:

**Comment by willianjusten** [comment]
A @jugoncalves passou um CSV com alguns dados. Como eu ainda não cheguei em casa não pude dar analisada, mas creio que devemos ter mais infos sim.

**Comment by BrunoKinoshita** [comment]
É, eu dei uma lida por cima quando eu chegar em casa vai da pra olhar direito

**Comment by jugoncalves** [comment]
Eu olhei no MailChimp e só exporta aquilo lá mesmo.
